version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: ./docker/go-air/Dockerfile
    ports:
      - 80:8000
    volumes:
      - .:/app
  postgres:
    image: 'postgres:alpine'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data/
volumes:
  postgres-db:
